version: '3.3'
services:
  gender:
    build:
      context: ./docker
      dockerfile: Dockerfile
    shm_size: '16gb'
    container_name: gender
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - 11501:11501   # jupyter
      - 6006:6006    # tensorboard
    volumes:
      - ./:/notebooks
    entrypoint: jupyter lab --ip 0.0.0.0 --port 11501 --allow-root --NotebookApp.password='' --NotebookApp.token=''
